services:
  redis:
    image: 'redis:latest'
    container_name: 'solana-safari-redis'
    ports:
      - '6379:6379'
    networks:
      - solana-safari-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'solana-safari-app'
    ports:
      - '3000:3000'
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - solana-safari-network
    env_file:
      - .env
    command: ['npm', 'run', 'start:prod']

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - solana-safari-network
    env_file:
      - .env
    command: ['npm', 'run', 'start:worker']
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

networks:
  solana-safari-network:
    driver: bridge
