const SOLANA_CONNECTION = 'SOLANA_CONNECTION';
const SOLANA_RPC_URL = 'SOLANA_RPC_URL';
const METAPLEX_INSTANCE = 'METAPLEX_INSTANCE';

export { SOLANA_CONNECTION, SOLANA_RPC_URL, METAPLEX_INSTANCE };
