const SOLANA_CONNECTION = 'SOLANA_CONNECTION';
const SOLANA_RPC_URL = 'SOLANA_RPC_URL';
const METAPLEX_INSTANCE = 'METAPLEX_INSTANCE';
const COINGECKO_API_URL = 'COINGECKO_API_URL';
const COINGECKO_API_KEY = 'COINGECKO_API_KEY';

export {
  SOLANA_CONNECTION,
  SOLANA_RPC_URL,
  METAPLEX_INSTANCE,
  COINGECKO_API_URL,
  COINGECKO_API_KEY,
};
